START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260903125233_AddQrCheckIn') THEN
    ALTER TABLE "Registrations" ADD "CheckedInAt" timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260903125233_AddQrCheckIn') THEN
    CREATE TABLE "EventCheckInSessions" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "EventId" integer NOT NULL,
        "TokenHash" character varying(64) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "ExpiresAt" timestamp with time zone NOT NULL,
        "IsActive" boolean NOT NULL,
        CONSTRAINT "PK_EventCheckInSessions" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_EventCheckInSessions_Events_EventId" FOREIGN KEY ("EventId") REFERENCES "Events" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260903125233_AddQrCheckIn') THEN
    CREATE INDEX "IX_EventCheckInSessions_EventId" ON "EventCheckInSessions" ("EventId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260903125233_AddQrCheckIn') THEN
    CREATE INDEX "IX_EventCheckInSessions_ExpiresAt" ON "EventCheckInSessions" ("ExpiresAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260903125233_AddQrCheckIn') THEN
    CREATE UNIQUE INDEX "IX_EventCheckInSessions_TokenHash" ON "EventCheckInSessions" ("TokenHash");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260903125233_AddQrCheckIn') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260903125233_AddQrCheckIn', '10.0.10');
    END IF;
END $EF$;
COMMIT;

